### ISSUE TITLE
ng2开发后的项目文件要做什么处理呢，在发布到服务器之前？

### ISSUE THREAD

**Issue by helloyxw** [kittencup/angular2-ama-cn#102]
平常项目开发完后文件要合并压缩，版本管理等。ng2的项目开发完后要做什么处理呢？
另外ts文件编译为js文件了，而运行时是运行js文件吧，在发布代码前是否要去除ts 文件和map文件呢？

**Comment by kittencup** [comment]
使用gulp + webpack.. 来处理，这块已经和本issue无关。
