### ISSUE TITLE
angular2-rest.d.ts 文件名里面的d是什么含义

### ISSUE THREAD

**Issue by iloveyo123u1** [kittencup/angular2-ama-cn#13]
有的文件里面没有，有的却有

这是表示什么含义呢

**Comment by kittencup** [comment]
TypeScript 设计的目标之一就是重用现有的 JavaScript 类库, 而它实现这一点则是通过 *.d.ts 声明文件, 为原有 JS 文件和现有 TS 项目搭桥.

**Comment by iloveyo123u1** [comment]
谢谢

**Comment by iloveyo123u1** [comment]
@kittencup  谢谢
