### ISSUE TITLE
在点击显示隐藏中，如果刷新页面怎么让他点击状态不改变

### ISSUE THREAD

**Issue by anghuang** [kittencup/angular2-ama-cn#130]
<input type="button" value="1222" (click)='isShow=!isShow'/>
		<div [style.display]='isShow?"block":"none"' >333</div>

**Comment by anghuang** [comment]
<input type="button" value="1222" (click)='isShow=!isShow'/>
		<div [style.display]='isShow?"block":"none"' >333</div>

**Comment by kittencup** [comment]
这个和ng2没关系。
