### ISSUE TITLE
关于怎么解决用户浏览器缓存的问题

### ISSUE THREAD

**Issue by coollemen** [kittencup/angular2-ama-cn#147]
我在服务器上部署网站后，客户端可以正常使用。但当我修改了一些页面布局，小bug后，对服务器进行了更新，但客户端显示的还是旧的页面。当我F12开发中模式刷新后，新的页面出来了，能正常使用。但当我关闭浏览器重新打开后，无论怎么刷新，都是旧的页面？这是什么问题呢？

**Comment by kittencup** [comment]
该问题可以在群里问。不属于ng2问题
