### ISSUE TITLE
有没有加载页面的动画，当数据加载完成，动画才消失，页面才可以操作

### ISSUE THREAD

**Issue by iloveyo123u1** [kittencup/angular2-ama-cn#15]
类似这种 https://cgross.github.io/angular-busy/demo/

，目前貌似还没有ng2 版本的

**Comment by kittencup** [comment]
自己撸个很简单。。angular 1我也是自己撸的。。 可以看下ionic2的实现
https://github.com/driftyco/ionic/tree/2.0
