### ISSUE TITLE
angular2+bootstrap 显示了菜单栏，如何隐藏用户没有权限查看的菜单按钮

### ISSUE THREAD

**Issue by ghost** [kittencup/angular2-ama-cn#167]
菜单有：人事管理、用户管理、离职管理， 等等

有些菜单，普通用户是没有权限查看和访问的

那么该如何弄呢

我初步想到的办法是，服务器提供一个api接口 比如 /getQuanXian ，默认返回当前用户对于每个菜单的访问权限

然后在angular2里面判断，如果用户不够权限，就隐藏菜单

但是我不知道如何高效便利的 完成这个需求

大家有什么可以指点一下的吗

**Comment by Imporial** [comment]
鄙人理解，不需要在前台即时变化的东西，没必要在脚本中判断，后台取好就行了，这就不是angular的范畴了

**Comment by hstarorg** [comment]
赞同楼上，getMenuData这个api返回的就是当前这个人有权限访问的菜单数据。

**Comment by ghost** [comment]
谢谢楼上两位

**Comment by ghost** [comment]
谢谢 @Imporial @hstarorg

**Comment by kittencup** [comment]
建议看看权限系统， rbac或者acl 然后加载用户权限，为每个页面或者元素创建权限，如果用户没有权限，可以不显示
