### ISSUE TITLE
rc1 代码写好了，如何压缩打包

### ISSUE THREAD

**Issue by ghost** [kittencup/angular2-ama-cn#168]
我的代码用的是rc1，和官方的demo一样 https://angular.io/docs/ts/latest/quickstart.html

弄好后，就直接可以运行了

现在我想打包压缩放到服务器上去
请问该怎么操作呢
我是个新手 ，网上没有找到对应方案

**Comment by kittencup** [comment]
webpack gulp 都可以

**Comment by hstarorg** [comment]
[https://github.com/hstarorg/HstarDemoProject/tree/master/angular2_demo/webpack-in-angular2](https://github.com/hstarorg/HstarDemoProject/tree/master/angular2_demo/webpack-in-angular2) 在Angular2中使用webpack打包，最基本的设置。你可以参考下。

**Comment by kunl** [comment]
有对应的  systemBuild 方案，具体脚本 [bundle.js](https://github.com/kunl/ng2/blob/gh-pages/bundle.js)

**Comment by ghost** [comment]
用angular-cli 直接build 就可以用了， 不过貌似最后的文件还是有点大

**Comment by Shyam-Chen** [comment]
https://github.com/mgechev/angular2-seed

gulp + systemjs
