### ISSUE TITLE
如何在ng2.0中实现ng1.x的replace：true

### ISSUE THREAD

**Issue by vthinkxie** [kittencup/angular2-ama-cn#169]
看了一下，angular官方已经决定在2.0中不支持去掉外层wrapper的参数了
在ng2.0中怎么才能实现这个特性？
比如
`<test-content></test-content>`
最后实际的html变成内层的template，例如`<div></div>`

**Comment by 694551594** [comment]
貌似只能用 [div] 类似这样的选择器了。

**Comment by kittencup** [comment]
实现不了吧 这个需求我们在很早时就再issues上提过了，官方还是决定不去掉。也没办法。
多一层会导致很多UI库迁移到angular2上比较麻烦

**Comment by hstarorg** [comment]
这个特丑，哎。
