### ISSUE TITLE
angular是不是  不适合写前台啊，感觉写前台太重了，一次加载几百个文件

### ISSUE THREAD

**Issue by ghost** [kittencup/angular2-ama-cn#172]
用angular-cli    打包后的文件，请求依然有几百个，2M+的体积，太大了

如果写后台的话，加载的速度慢一点还可以忍受，毕竟都是自己人访问

但是前台，是给客户访问的，不可能让客户等几十秒哇

主要也没有用别的东西

体积好大，项目就几个小模块

**Comment by lococo--0** [comment]
打包，压缩，gzip做处理 ·· 最后整个@angular加上所有zone，reflect这些polyfill，再加上es6shim大概有200kb

**Comment by ghost** [comment]
@lococo--0  这么小啊，求助 大神如何实现的

我用angular-cli      执行ng build 后， 输出的整个项目20多M  其中19M是angular本身的体积

**Comment by lococo--0** [comment]
19M？还是1.9M？

**Comment by ghost** [comment]
@lococo--0  19M多   接近20M

**Comment by lococo--0** [comment]
周末我写个打包构建教程

**Comment by qidongyou** [comment]
19M会不会太大了。

**Comment by ghost** [comment]
@lococo--0  多谢大神    要是能围绕angular-cli 来写就好了  多谢

**Comment by hstarorg** [comment]
使用webpack打包。polyfilles大概500k，angular2大概有2.3M，合计近3M，还可以压缩加gzip。这样处理之后就非常小了。

**Comment by ghost** [comment]
解决方法：执行 ng s -prod  就会生成很小的文件，一个项目大概几百KB
