### ISSUE TITLE
ng2 route,怎么样设置子路由，是否支持sticky

### ISSUE THREAD

**Issue by acivan** [kittencup/angular2-ama-cn#179]

**Comment by hstarorg** [comment]
如果你是用的rc版本，然后路由用的是`@angular/router`,那你只需要在组件上增加@Routes([])装饰就可以了。

如果是用的`@angular/router-depracated`,那么在配置一级路由的时候，path配置为`'/home/...'`

**Comment by hstarorg** [comment]
Angular2过期路由测试[https://github.com/hstarorg/HstarDemoProject/tree/master/angular2_demo/angular2-router-deprecated-test](https://github.com/hstarorg/HstarDemoProject/tree/master/angular2_demo/angular2-router-deprecated-test)

Angular2路由测试：[https://github.com/hstarorg/HstarDemoProject/tree/master/angular2_demo/angular2-router-test](https://github.com/hstarorg/HstarDemoProject/tree/master/angular2_demo/angular2-router-test)

**Comment by acivan** [comment]
Due to changes in the router, route generation has been temporarily disabled. You can find more information about the new router here: http://victorsavkin.com/post/145672529346/angular-router

**Comment by SolitaryMensch** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，感谢您的来信，我将尽快给您回复。
