### ISSUE TITLE
ng2 与webpack 整合，产品模式问题

### ISSUE THREAD

**Issue by CK110** [kittencup/angular2-ama-cn#180]
求有经验的大神告知，使用产品模式的webpack配置文件，生成dist 目录 ，是不是意味着我的生产环境的服务器只需要dist 目录，比如说我直接将dist目录放入tomcat ，但是我发现出错。

![image](https://cloud.githubusercontent.com/assets/9956098/16330013/e59e4ede-3a18-11e6-99fb-b017392e7a93.png)

![image](https://cloud.githubusercontent.com/assets/9956098/16330043/23fe0a5c-3a19-11e6-9c44-cc548453e3f1.png)

求告知 怎么部署 最终产品环境 是怎么gao搞的

**Comment by hstarorg** [comment]
直接拷贝dist目录下的内容到tomcat。

**Comment by CK110** [comment]
@hstarorg 
这是我的dist 文件
![image](https://cloud.githubusercontent.com/assets/9956098/16332132/ed9f6754-3a26-11e6-9f14-d2083cd305fd.png)

---

tomcat 配置完后，启动tomcat ，只能默认加载到index.html ，那些css，js 文件找不到
![image](https://cloud.githubusercontent.com/assets/9956098/16332173/2ab2a322-3a27-11e6-8b84-a9d037105811.png)

---

![image](https://cloud.githubusercontent.com/assets/9956098/16332204/5c9da580-3a27-11e6-8f69-29030303c3bb.png)

不知道是什么原因呢

**Comment by hstarorg** [comment]
请不要包含把dist目录放到tomcat中去，你当前的目录，资源文件应该是/dist/xxx.js，但实际不是，所以找不到。

**Comment by CK110** [comment]
@hstarorg 谢谢
