### ISSUE TITLE
哪位朋友可以分享下webpack+angular的优化文章呢，如何最大化压缩体积

### ISSUE THREAD

**Issue by ghost** [kittencup/angular2-ama-cn#181]
https://github.com/AngularClass/angular2-webpack-starter

我用过angular-cli  压缩后体积还是有大概1m左右， 我听群里的群友说可以到300KB 使用webpack，不知道他们是如何优化的，有朋友可以分享下方法吗

**Comment by kittencup** [comment]
http://engineering.invisionapp.com/post/optimizing-webpack/

http://mp.weixin.qq.com/s?__biz=MzI2NzExNTczMw==&mid=2653284910&idx=1&sn=77f0675205bcb2265745b377a2c331d5#rd

**Comment by ghost** [comment]
tks
