### ISSUE TITLE
我封装了一个对话框的服务，第一次能弹出对话框，关闭后再调用无法弹出对话框？

### ISSUE THREAD

**Issue by ruanzy** [kittencup/angular2-ama-cn#182]
我已解决。tks

**Comment by ruanzy** [comment]
`@Injectable()
export class Box {
	public dialogPromise:Promise<DD>;
	public dialogPromise2:Promise;
	constructor(public dynamicComponentLoader:DynamicComponentLoader,
                @Inject(forwardRef(() => App)) private app: App, private logger: Logger) {
	}

	open(options:Object) {
		var loader = this.dynamicComponentLoader;
		var logger = this.logger;
		this.dialogPromise = loader.loadNextToLocation(DD, this.app.elementRef);
		this.dialogPromise2 = this.dialogPromise.then((cr: ComponentRef) => {
		        var ins: 动态调用的组件 = cr.instance;
		        ins.options = $.extend({}, ins.options, options);
		        ins.setCss({
		        	width: options.width,
		        	top: 60
		        });
		        loader.loadIntoLocation(options.cmp, ins.element, 'kkk').then((cr: ComponentRef) => {
		        	ins.isActive = true;
		        	let h = ins.getHeight();
		        	logger.log(h);
		        });
		});
		
	}        
}


@Component({
	selector: 'alert-dialog',
	templateUrl: 'app/common/views/dialog.html?_=' + new Date(),
})
export class DD {
	options: Object = {
		title : 'title',
		content : '',
		closable : true
	};
	constructor(private element: ElementRef, private logger: Logger) {
		this.logger.log(this.options);
	} 
	close(){
		this.element.nativeElement.remove(); 
    	this.ngOnDestroy() 
	}
}

//dialog.html
<div class="wrapper">
	<div class="dialog open">
		<div class="modal-header bg-xx" style="padding:10px;">
			<a *ngIf="options.closable" type="button" class="close" (click)="close()"><span>&#215;</span></a>
			<h4 class="modal-title"><i class='fa fa-windowe'></i> {{options.title}}</h4>
		</div>
		<div class="modal-body"><div #kkk></div></div>
		<div class='modal-footer' *ngIf="options.buttons"></div>
	</div>
	<div class='masker'></div>
</div>`

**Comment by ruanzy** [comment]
调用box
`       this.box.open({
       	title :'新增监控',
       	width : 600,
       	content :'可拉伸的拉大手',
       	cmp : AddMonitor
       });`

**Comment by keyiis** [comment]
@ruanzy 怎么解决的啊？
