### ISSUE TITLE
ng2 SPA相关

### ISSUE THREAD

**Issue by Coca-code** [kittencup/angular2-ama-cn#186]
问题比较散：
1. 对移动webapp，单页，还是多页比较适合，ng2适合吗？
2. 有ng2的移动webapp的generator吗？有个小要求：基于ES6 + Webpack
3. 把ng2做的h5应用嵌在原生应用里，当离线了，原生可以，h5页怎么保证可以浏览？

谢谢。

**Comment by hstarorg** [comment]
1、一定webapp，单页多页均可。建议单页，搭配路由，体验更佳。
2、自己写...
3、离线了，一般不能浏览。不过，要实现离线浏览，可以用Application Cache。

**Comment by Coca-code** [comment]
感谢回复。

第三问，我也是用h5的新特性，离线浏览技术。。。

前段时间，看见传智播客一个影月播放器，用ng技术，但只是1.x，我想找ng2 + webpack 的spa单页项目seed,git上没有。为难了。。

2016-06-29 10:50 GMT+08:00 hstar notifications@github.com:

> 1、一定webapp，单页多页均可。建议单页，搭配路由，体验更佳。
> 2、自己写...
> 3、离线了，一般不能浏览。不过，要实现离线浏览，可以用Application Cache。
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/kittencup/angular2-ama-cn/issues/186#issuecomment-229242749,
> or mute the thread
> https://github.com/notifications/unsubscribe/AL0E3eqEO5x5xZAeL2uBLfPXe3uXWfKcks5qQd19gaJpZM4JAs_Y
> .

## 

♛
－－－－－－－－－－－－－－－－
_殷敏峰_    互联网／前端
－－－－－－－－－－－－－－－－

英文名：(Bruce.Yin)

手机：17091363566

地址：上海工作

座右铭：“Stay foolish,stay hungry”

爱好：旅游 火锅

－－－－－－－－－－－－－－－－－－－

微信：ymf_wx1981

邮箱：minfengyin@gmail.com

Github：https://github.com/Coca-code?tab=repositories

－－－－－－－－－－－－－－－－－－－

**Comment by hstarorg** [comment]
有的。angular2-seed.。还有带webpack的，挺多的。

**Comment by Coca-code** [comment]
​那我仔细找找​

2016-06-29 13:12 GMT+08:00 hstar notifications@github.com:

> 有的。angular2-seed.。还有带webpack的，挺多的。
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/kittencup/angular2-ama-cn/issues/186#issuecomment-229258097,
> or mute the thread
> https://github.com/notifications/unsubscribe/AL0E3TPN5L7Y8tLhjPEf0baI5Nc_JYGkks5qQf6zgaJpZM4JAs_Y
> .

## 

♛
－－－－－－－－－－－－－－－－
_殷敏峰_    互联网／前端
－－－－－－－－－－－－－－－－

英文名：(Bruce.Yin)

手机：17091363566

地址：上海工作

座右铭：“Stay foolish,stay hungry”

爱好：旅游 火锅

－－－－－－－－－－－－－－－－－－－

微信：ymf_wx1981

邮箱：minfengyin@gmail.com

Github：https://github.com/Coca-code?tab=repositories

－－－－－－－－－－－－－－－－－－－

**Comment by Xiahl1990** [comment]
https://github.com/AngularClass/angular2-webpack-starter
这个你可以参考下！

**Comment by Coca-code** [comment]
现在觉得ts比较适合ng
