### ISSUE TITLE
求助:ts中引用了window下的变量编译报错

### ISSUE THREAD

**Issue by caoren** [kittencup/angular2-ama-cn#196]
const electron = System._nodeRequire('electron');
编译报错
app/services/chat.ts(9,18): error TS2304: Cannot find name 'System'.

**Comment by lococo--0** [comment]
试试`window['System']`去引用

**Comment by caoren** [comment]
一样的报错，这个应该是typescript的打包问题，就是不知道怎么屏蔽这种错误，生成后的js一样能运行。

**Comment by lococo--0** [comment]
对 ·· 这个只是个提醒式的Err，因为window的里面没有System这个attribute，window['System']._nodeRequire('electron') 这样就不会报错了

**Comment by hstarorg** [comment]
`declare var System;`

**Comment by caoren** [comment]
@lococo--0 ，果然可以，非常感谢。
