### ISSUE TITLE
ng-2,为什么我调用后端api出现问题？

### ISSUE THREAD

**Issue by justb** [kittencup/angular2-ama-cn#213]
![x9234mgoc 7mb 2y c30 uh](https://cloud.githubusercontent.com/assets/22002343/18244121/f7d04a4c-7390-11e6-9d91-546c5d451f82.png)
![_ 33vh_5fe34j7 4pkdpn](https://cloud.githubusercontent.com/assets/22002343/18244129/00ba342e-7391-11e6-8bbf-060fe7727701.png)

**Comment by AganYa** [comment]
在后端设置好跨域访问了么？
