### ISSUE TITLE
Angular 2 如何解决 SEO 问题

### ISSUE THREAD

**Issue by lijiakof** [kittencup/angular2-ama-cn#218]
Angular 2 解决了 SEO 的问题，可以在服务端渲染应用的首屏，请问如何做到？

**Comment by yyjazsf** [comment]
服务端渲染应用的首屏   https://github.com/angular/universal

**Comment by lijiakof** [comment]
非常感谢，我最近在研究 Angular 2 ，准备把之前的 Angular 1.x 的网站重构过来。之前的 SEO 采用的 Prerender 技术。我再研究一下 Universal 看看。
