### ISSUE TITLE
@Component 不支持参数directives

### ISSUE THREAD

**Issue by wisdomofgod** [kittencup/angular2-ama-cn#227]
看到很多局部组件依赖通过
directives参数来定义
但我使用时编译报错，提示未定义该参数
翻源码 angualr/core/src/metadata.d.ts 该类下确实没有定义directives参数

目前只能通过@NgModul来定义组件依赖
请问是有什么时候不当的地方嘛？

报错部分：
Argument of type '{ selector: string; directives: typeof HeaderNav[]; template: any; }' is not assignable to parameter of type 'ComponentMetadataType'.
  Object literal may only specify known properties, and 'directives' does not exist in type 'ComponentMetadataType'.

**Comment by hstarorg** [comment]
2.0 final 已经不支持该用法了，请确认版本。

**Comment by wisdomofgod** [comment]
是final版本，那么请问有什么替代方法吗？  我看到官方手册里在Component的解释里 也是说使用NgModul

**Comment by hstarorg** [comment]
请使用NgModule，建议重新看一下正式版的语法。和RC5之前变化有点大。
