### ISSUE TITLE
angular2 动态按需加载样式文件思路

### ISSUE THREAD

**Issue by wuzhouyang** [kittencup/angular2-ama-cn#231]
项目已经分割为多个特性模块了，都是按需加载。现在想实现多主题功能，就是想要用户选择主题时才按需加载对应的样式文件并应用。是个什么思路？

**Comment by jiayisheji** [comment]
webpack按需加载

**Comment by wuzhouyang** [comment]
我是说组件的动态样式，单纯webpack就可以搞？

**Comment by ipengyo** [comment]
直接加css 盖掉以前的样式 不可用吗？

**Comment by yulucui** [comment]
有思路了吗？我现在也遇到同样的问题

**Comment by hstarorg** [comment]
https://github.com/hstarorg/angular-modular-platform/blob/master/src/common_module/services/module-loader.service.ts  动态设定link标签。
