### ISSUE TITLE
angular2 登录session过期跳转到登录页面，这个怎么加？在哪里加？

### ISSUE THREAD

**Issue by HALOH** [kittencup/angular2-ama-cn#244]
angular2 登录session过期跳转到登录页面，这个怎么加？在哪里加？

**Comment by hstarorg** [comment]
自己封装一下ajax请求。然后对401做拦截。根据实际情况跳转到登录页面。

**Comment by wut1** [comment]
https://angular.cn/docs/ts/latest/guide/router.html#!#guards
