### ISSUE TITLE
如何不显示ng-component标签

### ISSUE THREAD

**Issue by coloz** [kittencup/angular2-ama-cn#267]
添加的动态组件都带有ng-component标签，有没办法不要这个标签

**Comment by jiayisheji** [comment]
ng-component是拥抱了web component标准，自定义标签更有语义化，Angular做了很多处理，例如css里的:host

**Comment by coloz** [comment]
@jiayisheji 有没办法不要这个标签呢?

**Comment by jiayisheji** [comment]
不能，你可以用指令Directive，不要用组件Component了

**Comment by coloz** [comment]
@jiayisheji 感谢解答

**Comment by jiayisheji** [comment]
@coloz 可以用选择器

selector may be declared as one of the following:

- element-name: select by element name.
- .class: select by class name.
- [attribute]: select by attribute name.
- [attribute=value]: select by attribute name and value.
- :not(sub_selector): select only if the element does not match the sub_selector.
- selector1, selector2: select if either selector1 or selector2 matches.

不想用ng-component可以用div[ng-component] 不过这样tslint会报错 写在html的时候就像写指令一样
