### ISSUE TITLE
ng-book 2 翻译讨论及提问

### ISSUE THREAD

**Issue by kittencup** [kittencup/angular2-ama-cn#28]
[ng-book 2 翻译正在进行中](https://github.com/kittencup/angular2-ama-cn/issues/24) ，这些issue关闭讨论，主要就是发布翻译内容。

翻译的比较快，中间可能会出现很多问题，如有问题可在此issue中提出

**Comment by kunl** [comment]
翻译可以按章节 分成几个 issue 啊，搞一个不方便了。单独搞个标签

**Comment by kittencup** [comment]
= = 我考虑下

**Comment by leshin** [comment]
放到gitbook里，看着更方便。
