### ISSUE TITLE
angular2 的服务 好处究竟体现在何处，是不是个鸡肋的东西

### ISSUE THREAD

**Issue by iloveyo123u1** [kittencup/angular2-ama-cn#3]
谢谢

**Comment by kittencup** [comment]
ng2的服务 就是一个普通的class ,好处就是 任何的class都能成为一个服务。。

**Comment by iloveyo123u1** [comment]
理解了 3q

**Comment by heboliufengjie** [comment]
给这个链接参考，有助于理解服务  
http://www.oschina.net/translate/angularjs-factory-vs-service-vs-provider

**Comment by iloveyo123u1** [comment]
@heboliufengjie    thanks

**Comment by iloveyo123u1** [comment]
@kittencup  结贴
