### ISSUE TITLE
有下面2个问题，希望详细解答一下

### ISSUE THREAD

**Issue by NeverlandForKi** [kittencup/angular2-ama-cn#4]
1，ng2和ng1的区别都有哪些？
2，双向数据绑定和单向数据绑定的优劣，即双向数据绑定有什么优势劣势，单项数据绑定有什么优势劣势

**Comment by iloveyo123u1** [comment]
hi,你好

我觉得这2个问题，基本上网上公开的中文资料（关于angular2的中文新闻）  基本都介绍了 两者的区别，和关于双向绑定 单向绑定的优劣势

angular2 肯定是各方面都要比ng1 好很多 ，目前有beta版本了，我已经在公司项目中用上了ng2

正式版出来以后，会更加强大 ，好用
 


期待 有大神回答你的问题 :)

**Comment by kittencup** [comment]
不要在1个issues中提多个问题。 我帮你分开

**Comment by iloveyo123u1** [comment]
http://www.oschina.net/translate/when-should-you-use-angular
