### ISSUE TITLE
ionic2中list中的infinite是否还未实现，为什么我使用一直报错？

### ISSUE THREAD

**Issue by qiongshusheng** [kittencup/angular2-ama-cn#67]

**Comment by kittencup** [comment]
看了下源码 完全没看到 有 infinite功能

**Comment by qiongshusheng** [comment]
测试例子里面不是有一个infinite的list吗？

**Comment by kittencup** [comment]
报什么错贴下吧。。

**Comment by qiongshusheng** [comment]
![image](https://cloud.githubusercontent.com/assets/13391396/12573568/99ce5872-c435-11e5-9768-df8caf3bb692.png)

**Comment by kittencup** [comment]
ItemCellTemplate 代码看看 这个是语法问题 和 ionic2没关系

**Comment by kittencup** [comment]
建议贴下相关代码。

**Comment by qiongshusheng** [comment]
代码在ionic2的源码里面components==》list==》test==》infinite==》index.ts

**Comment by kittencup** [comment]
我看了下 感觉代码没什么问题。。具体什么原因要调试 我这边暂时也没用过ionice2

**Comment by qiongshusheng** [comment]
找了好长时间，一直报错，感觉是因为框架还没写完，这块还不完整的原因，楼主有时间可否帮我写一个类似于ionic1里面的collection-repeat一样的大数据列表的例子，thank you！

**Comment by qiongshusheng** [comment]
![image](https://cloud.githubusercontent.com/assets/13391396/12804096/d213fa10-cb2a-11e5-94e1-6d9875e129a4.png)
表示还没有实现这个功能，以后可能会实现！
