### ISSUE TITLE
[建议]希望能把ngbook的翻译放到gitbook上

### ISSUE THREAD

**Issue by axetroy** [kittencup/angular2-ama-cn#68]
这样这样整理出来的资料有意义好多，方便更多人学习

**Comment by kittencup** [comment]
现在还未正式版，很多内容还会修改，以后会考虑，但我还是希望能有一整套问题，教大家学习angular 2，而并非是看书，而且暂时觉得ng-book2写的并不好。

**Comment by kittencup** [comment]
关于ng-book的讨论请到 [ng-book 2 总目录](https://github.com/kittencup/angular2-ama-cn/issues/43) 讨论
