### ISSUE TITLE
angular2 中的interface是否可有可无

### ISSUE THREAD

**Issue by iloveyo123u1** [kittencup/angular2-ama-cn#8]
在看到这个代码 https://github.com/ghpabs/angular2-seed-project/blob/master/src/scripts/todo/todo.interface.ts

感觉interface 就是对 某个对象  制定了一个格式，一个结构
## 因为这是一个模块化的世界，所以如果我们想定义一个对象，比如一个英雄，我们要给他一个id，给他一个名字。在Angular2 里面，我们可以给他定义个一个interface，比如:

interface Hero {
  id: number;
  name: string;
}

var HEROES: Hero[] = [
    { "id": 11, "name": "Mr. Nice" },
    { "id": 12, "name": "Narco" }
## 那么，为何不在 使用的时候直接 写Object[]，声明为 

var HEROES: Object[] = [
    { "id": 11, "name": "Mr. Nice" },
    { "id": 12, "name": "Narco" }
## ]

那么定义interface 是否是一个可有可无的呢
interface在什么项目中，起着 如何的作用呢

**Comment by kittencup** [comment]
interface起了强制作用，你的HEROES中每一个对象必须有id和name属性，如果你用Object就没这个效果
而且你用Object后 ，想`HEROES[0].id`这样访问应该是报错了

**Comment by iloveyo123u1** [comment]
@kittencup   理解了 多谢 麻烦结贴

**Comment by kittencup** [comment]
帖不会结束，大家可以继续探讨
