### ISSUE TITLE
ng2如何手动跳转（使用代码）

### ISSUE THREAD

**Issue by HereSinceres** [kittencup/angular2-ama-cn#92]
1.   this.location.go('/about');这个只能改变url地址，但是界面不变。
    2.   this.router.navigate(['./ById', {id: id}]);这个必须当前组件配置@router

**Comment by kittencup** [comment]
`this.router.navigate(['/ParentRouter']);`

用`/`可以访问顶层路由，该方法没任何问题。

**Comment by HereSinceres** [comment]
在ng1 ui-router中可以使用  $state.go('contacts.details', { contactId: randId });这样的方法跳转指定路由。
在ng2 中使用什么方法跳转

**Comment by kittencup** [comment]
上面不是答了么。
