### ISSUE TITLE
组件不显示selector标签，直接显示真实内容。

### ISSUE THREAD

**Issue by HereSinceres** [kittencup/angular2-ama-cn#93]
在ng2 中定义组件了，在界面使用的使用如何不显示selector标签，直接显示真实内容。ng1中可以使用replace：true去除,ng2中如何做到？？？？
![image](https://cloud.githubusercontent.com/assets/11225986/13070251/19b42292-d4c6-11e5-8b38-1fd78616609d.png)

**Comment by kittencup** [comment]
没办法，ng2暂时肯定会有host element标签
