### ISSUE TITLE
请问为什么要用System.import('app.js')来加载应用，而不是直接用<script>标签

### ISSUE THREAD

**Issue by cstur** [kittencup/angular2-ama-cn#94]

**Comment by kittencup** [comment]
因为你编写的是ts或es6，不能直接在浏览器运行，通过Systemjs，会转换为浏览器可运行的js

**Comment by cstur** [comment]
我写的是ts然后tsc编译成js，而且target是es5为什么还是不行呢？

**Comment by kittencup** [comment]
1.这问题太过于笼统，可以具体贴下代码
2.这个问题也超出angular2范围了

**Comment by adu8419** [comment]
并不是一定要用systemjs  官网有说明 你可以使用其他 构建工具  比如gulp webpack 
如果你不用systemjs  当然 就不会 使用 System.import('app.js')来加载应用

**Comment by lococo--0** [comment]
@cstur 因为你ts转了es5之后原来的`import xxx`变成了`require xxx`，然而即使这样，浏览器也并不认识require这个函数，所以需要加入loader来实现require方法，systemjs就是一个loader，requirejs也是一个loader，还有seajs，esl等等，这些包都实现了require函数，但是每种实现的方式不一样

我这两天在写一个ng2构建相关的文章，会讲到loader这个问题，到时候贴给你

**Comment by adu8419** [comment]
@lococo--0   能麻烦贴在这 一起分享下么
