### ISSUE TITLE
ng2的Input 和 output 我这样理解对么

### ISSUE THREAD

**Issue by iloveyo123u1** [kittencup/angular2-ama-cn#95]
网上的文章貌似描述的有些抽象
我看了以后想想 是不是可以这样理解

比如：
<talk-cmp [talk]="someExp" (rate)="eventHandler($event.rating)"></talk-cmp>

input，   [talk]="someExp"  这个标签可以理解为一个专门的监听器，监听父组件传递过来的someExp参数，并存入自身组件的talk变；好像是开了个后门，允许且只允许父组件的someExp进入，一旦进入立刻抓进一个叫talk的牢房，

output ，(rate)="eventHandler($event.rating) 这个意思是， 当子组件的rate事件被触发，就执行父组件的eventHandler函数，并把子组件的参数$event.rating传递给父组件的eventHandler函数；就好像，当小孩子一哭（执行rate事件），他的母亲立刻把他抱在怀里（执行母亲的eventHandler），同时母亲获得了小孩子的一些参数（$event.rating）

好像我描述的不太妥当，但感觉似乎就是这么个意思，对吗， 另外 请问，应该去哪里学习 $even 这样的系统自身的一些参数呢

**Comment by kittencup** [comment]
大白话说的不错。。差不多把。

具体实现可以参考源码
